### ISSUE TITLE
Unicode support or provide option to define charset (encoding)

### ISSUE THREAD

**Issue by ivbeg** [evinism/mistql#121]
Please provide option to define character set (encoding). Right now files with unicode but non ASCII ain't supported.

Example JSON file attached
[data-20160919T0700.zip](https://github.com/evinism/mistql/files/8506085/data-20160919T0700.zip)

Command line _python -m mistql.cli "@" --file data-20160919T0700.json_

Error message
_Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\lib\site-packages\mistql\cli.py", line 64, in <module>
    raw_data = f.read()
  File "C:\Program Files\Python310\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 767: character maps to <undefined>_

**Comment by evinism** [comment]
Looks like there's a fair number of issues with unicode handling in windows using the python CLI. Basic utf-16 support was addressed in #123, more windows issues are repro'd in https://github.com/evinism/mistql/pull/124

**Comment by evinism** [comment]
If the windows tests are to be believed, this should be fixed on main. Will be pushed in the next release (0.4.8), likely to be pushed within the coming week. 

Related PRs: #123, #124, #125, #126

**Comment by evinism** [comment]
Released in 0.4.8
