### ISSUE TITLE
Determine whether to error on sorting one-element arrays with unsortable contents.

### ISSUE THREAD

**Issue by evinism** [evinism/mistql#133]
Right now. sorting only errors if there are two unsortable objects in an array. For example `sort [{}]` succeeds, but `sort [{}, {}]` fails. As this is a consequence of implementation rather than specification, we should come up with expected behavior.

**Comment by adamtrilling** [comment]
My feeling is, if we're going to error on multiple unsortable items, we should error on just one, too.

**Comment by evinism** [comment]
Agreed, let's go with that!
