### ISSUE TITLE
Using match function or =~ operator

### ISSUE THREAD

**Issue by mandolyte** [evinism/mistql#65]
The docs mention both the match function which will match a pattern (not sure it is a regex .. is it?) and the `=~` operator.

But in the "Try it Out" playgound, this does not work:
`events | filter email =~ "^h"`

It returns an empty array. I expected it to return the first entry where the email address is harold@example.com

I tried the match function and it doesn't work either (at least as best I could figure out how to use). This:
`events | match (regex "h*") email`

returns an error message "Expected 2 arguments, got 3".

I'd be happy to augment your documentation with examples of these two if someone will correct what I'm doing wrong.

**Comment by mandolyte** [comment]
Ugh... I kept playing and found something that works:
`events | filter email =~ (regex "^[hf]")`

**Comment by evinism** [comment]
Yep, filtering is the intended way to pare down an array. Thanks for the contribution! 

Getting these error messages to be a little cleaner is probably a good thing to do -- and/or it might be clean to make the match operator cast strings to regexes.
